# What is an array?
* Arrays can store data of a specific type. 
* Elements of arrays are stored in contiguous memory locations.
* They have unique location identifier.
* Size of array is predefined and can not be changed later on.




#Memory Allocation.

* They're alloted continuous memory space in computer memory.
* 2D or n-Dimensional arrays are treated like 1D arrays while allocating space in computer memory.



#Creating an Array {without NumPy}

from array import *                                                            
arrayName= array(typecode, {Initialisers})

In [1]:
from array import *
myArray= array('i', [1,2,3,4,5])
myArray

array('i', [1, 2, 3, 4, 5])

In [2]:
myArrayDouble= array('d', [1,2.4,5,3,6,1]) #double array
myArrayDouble

array('d', [1.0, 2.4, 5.0, 3.0, 6.0, 1.0])

## Insert, Traverse, Delete elements

### Insert

In [3]:

myArray.insert(0, 0) #0 is being added at first index, index 0
myArray

array('i', [0, 1, 2, 3, 4, 5])

In [4]:
myArray.insert(6, 6) # 6 is being inserted at index 6, end of array.
myArray

array('i', [0, 1, 2, 3, 4, 5, 6])

### Traversal

In [5]:
#Traversing means visiting all cells one by one.
def ArrayTraversal(array):
  for i in array:
    print(i)

In [6]:
ArrayTraversal(myArray)

0
1
2
3
4
5
6


### Access array element
* Access array element by index.
* Constant time operations. O(1) time and space complexity.

In [7]:
myArray[2:4]

array('i', [2, 3])

In [8]:
def accessElement(array, index):
    if index > len(array):
        print('Out of bounds index')
    else:
        print(array[index])

In [9]:
accessElement(myArray, 8)

Out of bounds index


In [10]:
accessElement(myArray, 6)

6


### Searching for an element in Array

In [11]:
print(myArray)

array('i', [0, 1, 2, 3, 4, 5, 6])


In [12]:
def searchInArray(array, value):
    for i in array:
        if i == value:
            return array.index(value)
    return 'The element does not exist in an array'

In [13]:
searchInArray(myArray, 2)

2

In [14]:
searchInArray(myArray, 8)

'The element does not exist in an array'

### Delete element from Array
* Elements need to be moved to make the memory space contiguous

In [15]:
print(myArray)

array('i', [0, 1, 2, 3, 4, 5, 6])


In [16]:
myArray.remove(1)  #Element with value 1 will be removed.
print(myArray)

array('i', [0, 2, 3, 4, 5, 6])


# One Dimensional Array Practice.

In [17]:
from array import *
my_array= array('i', [1,2,3,4,5]) #Create

In [18]:
for i in my_array:   #Access elements in array
    print(i)

1
2
3
4
5


In [19]:
#Add element to end of array using append method. Can also use .insert to insert at particular index.

my_array.append(6)
print(my_array)

array('i', [1, 2, 3, 4, 5, 6])


In [20]:
#Add element at particular index using insert 
my_array.insert(6, 7)  #insert 7 at index 6
print(my_array)

array('i', [1, 2, 3, 4, 5, 6, 7])


In [21]:
#Extend method

my_array.extend(array('i',[8,9,10,11]))
print(my_array)

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])


In [22]:
#Add items from list using fromlist() method

mylist= [12,13,14,15]
my_array.fromlist(mylist)  #Adding element from list 'mylist'
print(my_array)

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])


In [23]:
#remove element from array

my_array.remove(1) #remove first occurence of 1 from array
print(my_array)

array('i', [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])


In [24]:
#remove last element using pop method

my_array.pop()
print(my_array)

array('i', [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])


In [25]:
# find index of an element

print(my_array.index(9))

7


In [26]:
my_array.reverse()
print(my_array)

array('i', [14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2])


In [27]:
#Get array buffer information  through buffer.info method.
print(my_array.buffer_info()) 
#memory start location and number of elements

(140281085955312, 13)


In [28]:
#Number of times an element occurs in the array
my_array.append(11)
my_array.count(11)

2

In [29]:
# Convert integer array to string array
str_Temp= my_array.tostring()
print(str_Temp)

b'\x0e\x00\x00\x00\r\x00\x00\x00\x0c\x00\x00\x00\x0b\x00\x00\x00\n\x00\x00\x00\t\x00\x00\x00\x08\x00\x00\x00\x07\x00\x00\x00\x06\x00\x00\x00\x05\x00\x00\x00\x04\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x0b\x00\x00\x00'


In [30]:
#Convert array to list using tolist() method
my_list=my_array

In [31]:
my_list.tolist()

[14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 11]

In [32]:
#Append a string to char array using fromstring() method

ints= array('i')
ints.fromstring(str_Temp)
print(ints)

array('i', [14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 11])


In [33]:
my_array[5:9]

array('i', [9, 8, 7, 6])

# Two Dimensional Array

In [34]:
import numpy as np
twoDArray= np.array([ [10,15,16],
                      [17,32,76],
                      [7, 98,11]
                    ])
print(twoDArray)

[[10 15 16]
 [17 32 76]
 [ 7 98 11]]


## Insert row or column to array using the np.insert option

In [35]:
newtwoDArray= np.insert(twoDArray,0, [[0,1,2]], axis=1) #original array, position, new vector, axis
newtwoDArray

array([[ 0, 10, 15, 16],
       [ 1, 17, 32, 76],
       [ 2,  7, 98, 11]])

In [36]:
newtwoDArray= np.insert(newtwoDArray, 1, [5,5,5], axis= 1)
newtwoDArray

array([[ 0,  5, 10, 15, 16],
       [ 1,  5, 17, 32, 76],
       [ 2,  5,  7, 98, 11]])

In [37]:
#Append row/column using the np.append function

newtwoDArray= np.append(newtwoDArray, [[1,2,3,4,5]], axis=0)
newtwoDArray

#DON"T FORGET TO PUT DOUBLE PARANTHESIS WHEN ADDING/INSERTING ROWS OR COLUMNS.

array([[ 0,  5, 10, 15, 16],
       [ 1,  5, 17, 32, 76],
       [ 2,  5,  7, 98, 11],
       [ 1,  2,  3,  4,  5]])

## Traverse a 2D array.

In [43]:
for i in range (0,np.shape(newtwoDArray)[0]):
    for j in range (0,np.shape(newtwoDArray)[1]):
        print(newtwoDArray[i][j])

0
5
10
15
16
1
5
17
32
76
2
5
7
98
11
1
2
3
4
5


# Deleting row/column from array.

In [45]:
newtwoDArray

array([[ 0,  5, 10, 15, 16],
       [ 1,  5, 17, 32, 76],
       [ 2,  5,  7, 98, 11],
       [ 1,  2,  3,  4,  5]])

In [46]:
newRowRemovedArray= np.delete(newtwoDArray, -1, axis = 0) #array, index, and axis
print(newRowRemovedArray)

[[ 0  5 10 15 16]
 [ 1  5 17 32 76]
 [ 2  5  7 98 11]]


# Time Complexity for array operations

* Creation- O(1). Space Complexity is O(n)
* Insertion at begining of array/ middle of array- O(n)
* Insertion at end of array - O(1).
* Array Traversal- O(n) { if you're simply printing the elements of array }
* Accessing an array element by index takes constant space and time complexity. O(1)
* Searching for an element in an array has O(n) time complexity and O(1) space complexity.
* If last element is deleted the time complexity is O(1) since no elements need to shift, but otherwise its O(n). Space complexity is O(1)
* Creation of 2D array takes O(1) time complexity. Space Complexity is O(mn)
* Accessing an element of a 2D element takes O(1) time complexity and space complexity.
* Time complexity is O(mn), space complexity is O(1) for traversing through a 2D array.
* Linear search for element in 2D array has time complexity of O(mn)and space complexity of O(1).
* Deleting a row or column from a 2D array has O(mn) type complexity. 

<img src="./imagetcsc.png" style="height: 300px;"/>

<img src="./imagetcscd.png" style="height: 300px;"/>

# When to use and avoid arrays?

* Multiple variables from same data type.
* Randomly access a variable or value. Array offers O(1) time complexity.
* Same data type elements are allowed exclusively and they reserve memory.